# Generated by Django 5.2.6 on 2026-07-31 17:37

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When this record was soft-deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Additional metadata for this record",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this record is active (soft delete)",
            ),
        ),
    ]
