# Generated by Django 5.2.17 on 2026-10-05 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_use_soft_delete_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_price_id", ""), _negated=True),
                fields=("stripe_price_id",),
                name="billing_plan_unique_stripe_price_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_subscription_id", ""), _negated=True),
                fields=("stripe_subscription_id",),
                name="billing_subscription_unique_stripe_subscription_id",
            ),
        ),
    ]
