"""Core schemas package.

This module exports all schema classes for the core app.
"""

from core.schemas.api_key_schema import (
    APIKeyCreatedResponse,
    APIKeyResponse,
    CreateAPIKeyRequest,
    RevokeAPIKeyRequest,
    RotateAPIKeyResponse,
)
from core.schemas.auth_schema import (
    AuthStatusSchema,
    EmailVerificationSchema,
    LoginSchema,
    PasswordlessLoginRequest,
    PasswordlessLoginVerify,
    PasswordResetConfirmSchema,
    PasswordResetRequestSchema,
    RefreshTokenSchema,
    TokenSchema,
    UserLoginSchema,
)
from core.schemas.base_schema import (
    AuditSchema,
    BaseFilterSchema,
    BaseModelSchema,
    BaseSortSchema,
    BulkActionResponse,
    BulkActionSchema,
    CamelCaseSchema,
    DateRangeSchema,
    ErrorResponse,
    HealthCheckResponse,
    HealthStatus,
    IdResponse,
    MessageResponse,
    PaginatedResponse,
    PaginationMeta,
    ServiceHealth,
    SortOrder,
    StatusEnum,
    StatusUpdateSchema,
    SuccessResponse,
    TimestampSchema,
    ValidationErrorResponse,
    create_error_response,
    create_paginated_response,
    create_success_response,
)
from core.schemas.otp_schema import (
    OTPRequestSchema,
    OTPResponseSchema,
    OTPStatusSchema,
    OTPTokenVerifySchema,
    OTPVerifyResponseSchema,
    OTPVerifySchema,
    PasswordResetWithOTPSchema,
    ResendOTPSchema,
    SignupWithOTPSchema,
    TwoFactorSetupSchema,
    TwoFactorVerifySchema,
)
from core.schemas.user_schema import (
    ChangePasswordSchema,
    UserBasicSchema,
    UserDeleteSchema,
    UserLogoutSchema,
    UserPreferencesSchema,
    UserSchema,
    UserSignupSchema,
    UserStatsSchema,
    UserUpdateSchema,
)

__all__ = [
    # Auth schemas
    "AuthStatusSchema",
    "EmailVerificationSchema",
    "LoginSchema",
    "PasswordlessLoginRequest",
    "PasswordlessLoginVerify",
    "PasswordResetConfirmSchema",
    "PasswordResetRequestSchema",
    "RefreshTokenSchema",
    "TokenSchema",
    "UserLoginSchema",
    # OTP schemas
    "OTPRequestSchema",
    "OTPResponseSchema",
    "OTPStatusSchema",
    "OTPTokenVerifySchema",
    "OTPVerifyResponseSchema",
    "OTPVerifySchema",
    "PasswordResetWithOTPSchema",
    "ResendOTPSchema",
    "SignupWithOTPSchema",
    "TwoFactorSetupSchema",
    "TwoFactorVerifySchema",
    # User schemas
    "ChangePasswordSchema",
    "UserBasicSchema",
    "UserDeleteSchema",
    "UserLogoutSchema",
    "UserPreferencesSchema",
    "UserSchema",
    "UserSignupSchema",
    "UserStatsSchema",
    "UserUpdateSchema",
    # API Key schemas
    "APIKeyCreatedResponse",
    "APIKeyResponse",
    "CreateAPIKeyRequest",
    "RevokeAPIKeyRequest",
    "RotateAPIKeyResponse",
    # Base schemas
    "CamelCaseSchema",
    "AuditSchema",
    "BaseFilterSchema",
    "BaseModelSchema",
    "BaseSortSchema",
    "BulkActionResponse",
    "BulkActionSchema",
    "DateRangeSchema",
    "ErrorResponse",
    "HealthCheckResponse",
    "HealthStatus",
    "IdResponse",
    "MessageResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "ServiceHealth",
    "SortOrder",
    "StatusEnum",
    "StatusUpdateSchema",
    "SuccessResponse",
    "TimestampSchema",
    "ValidationErrorResponse",
    # Utility functions
    "create_error_response",
    "create_paginated_response",
    "create_success_response",
]
