# Generated by Django 5.2.6 on 2026-01-06 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="User ID, email, phone, or IP address",
                        max_length=255,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "LOGIN"),
                            ("SIGNUP_VERIFICATION", "SIGNUP_VERIFICATION"),
                            ("PASSWORD_RESET", "PASSWORD_RESET"),
                            ("EMAIL_CHANGE", "EMAIL_CHANGE"),
                            ("PHONE_VERIFICATION", "PHONE_VERIFICATION"),
                            ("TWO_FACTOR", "TWO_FACTOR"),
                            ("MAGIC_LINK", "MAGIC_LINK"),
                        ],
                        default="LOGIN",
                        help_text="Purpose of the OTP request",
                        max_length=50,
                    ),
                ),
                (
                    "request_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of requests in the current window"
                    ),
                ),
                (
                    "window_start",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Start of the rate limit window"
                    ),
                ),
                (
                    "blocked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="If blocked, when the block expires",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Rate Limit",
                "verbose_name_plural": "OTP Rate Limits",
            },
        ),
        migrations.AlterModelOptions(
            name="onetimepassword",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "One Time Password",
                "verbose_name_plural": "One Time Passwords",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of verification attempts"
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="6-digit numeric OTP code for mobile apps",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="delivery_method",
            field=models.CharField(
                choices=[("EMAIL", "EMAIL"), ("SMS", "SMS"), ("PUSH", "PUSH")],
                default="EMAIL",
                help_text="How the OTP was delivered",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the request", null=True
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=5, help_text="Maximum allowed verification attempts"
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional metadata"
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("LOGIN", "LOGIN"),
                    ("SIGNUP_VERIFICATION", "SIGNUP_VERIFICATION"),
                    ("PASSWORD_RESET", "PASSWORD_RESET"),
                    ("EMAIL_CHANGE", "EMAIL_CHANGE"),
                    ("PHONE_VERIFICATION", "PHONE_VERIFICATION"),
                    ("TWO_FACTOR", "TWO_FACTOR"),
                    ("MAGIC_LINK", "MAGIC_LINK"),
                ],
                default="LOGIN",
                help_text="Purpose of this OTP",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="used_at",
            field=models.DateTimeField(
                blank=True, help_text="When this OTP was used", null=True
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="user_agent",
            field=models.TextField(
                blank=True, default="", help_text="User agent of the request"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User's profile avatar",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short bio or description",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True, help_text="Whether to receive email notifications"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether the user account is active",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Whether the user's email is verified"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True, default="", help_text="User's location", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional metadata for the user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="", help_text="User's phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="push_notifications",
            field=models.BooleanField(
                default=True, help_text="Whether to receive push notifications"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="UTC", help_text="User's preferred timezone", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the user profile was last updated"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(
                blank=True, default="", help_text="User's website URL"
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this OTP was created"
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_at",
            field=models.DateTimeField(help_text="When this OTP expires"),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="is_used",
            field=models.BooleanField(
                default=False, help_text="Whether this OTP has been used"
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="token",
            field=models.CharField(
                help_text="Long token for magic links", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="user",
            field=models.ForeignKey(
                help_text="User this OTP belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When the user account was created",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="User's email address (used for login)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", help_text="User's first name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, help_text="Whether the user can access admin site"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False, help_text="Whether the user has all permissions"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, help_text="When the user last logged in", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", help_text="User's last name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="User's unique username",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="onetimepassword",
            index=models.Index(
                fields=["user", "purpose"], name="core_onetim_user_id_cb871a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetimepassword",
            index=models.Index(fields=["token"], name="core_onetim_token_37952d_idx"),
        ),
        migrations.AddIndex(
            model_name="onetimepassword",
            index=models.Index(
                fields=["code", "user"], name="core_onetim_code_c8037a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetimepassword",
            index=models.Index(
                fields=["expires_at"], name="core_onetim_expires_2b42c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetimepassword",
            index=models.Index(
                fields=["is_used"], name="core_onetim_is_used_c1953c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetimepassword",
            index=models.Index(
                fields=["created_at"], name="core_onetim_created_d747e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-date_joined"], name="core_user_date_jo_609b52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="core_user_is_acti_8c954f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified"], name="core_user_is_veri_959b73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpratelimit",
            index=models.Index(
                fields=["identifier", "purpose"], name="core_otprat_identif_ca4ba5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpratelimit",
            index=models.Index(
                fields=["window_start"], name="core_otprat_window__9c8f59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpratelimit",
            index=models.Index(
                fields=["blocked_until"], name="core_otprat_blocked_64cec2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="otpratelimit",
            unique_together={("identifier", "purpose")},
        ),
    ]
