# Generated by Django 5.2.6 on 2026-02-04 23:15

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_otpratelimit_alter_onetimepassword_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this feature flag",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for this feature flag (use snake_case)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what this feature flag controls",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("boolean", "BOOLEAN"),
                            ("percentage", "PERCENTAGE"),
                            ("user_list", "USER_LIST"),
                            ("ab_test", "AB_TEST"),
                        ],
                        default="boolean",
                        help_text="Type of feature flag",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Master switch - if False, flag is disabled for everyone",
                    ),
                ),
                (
                    "rollout_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of users to enable this flag for (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "user_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="List of user IDs that have this flag enabled",
                    ),
                ),
                (
                    "excluded_user_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="List of user IDs that are excluded from this flag",
                    ),
                ),
                (
                    "variants",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="A/B test variants with weights, e.g., {'control': 50, 'variant_a': 30, 'variant_b': 20}",
                    ),
                ),
                (
                    "default_variant",
                    models.CharField(
                        blank=True,
                        default="control",
                        help_text="Default variant for A/B tests",
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Advanced conditions for flag evaluation (e.g., user attributes, environment)",
                    ),
                ),
                (
                    "environments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="List of environments where this flag is active (empty = all)",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this flag should start being active",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this flag should stop being active",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional metadata for this flag",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Tags for organizing and filtering flags",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this flag was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this flag was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed (created, updated, deleted, enabled, disabled)",
                        max_length=50,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Details of the changes made",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.featureflag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag Audit Log",
                "verbose_name_plural": "Feature Flag Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this audit log entry",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("SOFT_DELETE", "Soft Delete"),
                            ("RESTORE", "Restore"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("API_REQUEST", "API Request"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("CUSTOM", "Custom Action"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "action_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of the action",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Email of the user (preserved even if user is deleted)",
                        max_length=254,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Name of the model that was affected",
                        max_length=255,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="ID of the object that was affected",
                        max_length=255,
                    ),
                ),
                (
                    "object_repr",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="String representation of the object",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON object containing the changes made",
                    ),
                ),
                (
                    "previous_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="State of the object before the change",
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="State of the object after the change",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        help_text="IP address of the request",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User agent string from the request",
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTTP method of the request",
                        max_length=10,
                    ),
                ),
                (
                    "request_path",
                    models.TextField(
                        blank=True, default="", help_text="URL path of the request"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Unique request ID for correlation",
                        max_length=255,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional contextual data",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the action failed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_auditl_timesta_189a84_idx"
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="core_auditl_action_f07419_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="core_auditl_user_id_2a1528_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-timestamp"],
                        name="core_auditl_model_n_9470ca_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="core_auditl_model_n_3fb686_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="core_auditl_ip_addr_71e206_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="core_auditl_request_2f651b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(fields=["name"], name="core_featur_name_d55661_idx"),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["enabled"], name="core_featur_enabled_fdcd98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["flag_type"], name="core_featur_flag_ty_a28d16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["-created_at"], name="core_featur_created_c079eb_idx"
            ),
        ),
    ]
