# Generated by Django 5.2.6 on 2026-02-04 23:17

import uuid

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_feature_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadLetterQueueEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Original Celery task ID",
                        max_length=255,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        db_index=True, help_text="Task name", max_length=255
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Task positional arguments",
                    ),
                ),
                (
                    "kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Task keyword arguments",
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(help_text="Exception class name", max_length=255),
                ),
                ("exception_message", models.TextField(help_text="Exception message")),
                (
                    "traceback",
                    models.TextField(
                        blank=True, default="", help_text="Full traceback"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="normal",
                        help_text="Priority level for retry",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts from DLQ"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, help_text="Maximum retry attempts from DLQ"
                    ),
                ),
                (
                    "last_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last retry was attempted",
                        null=True,
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this entry has been resolved",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes about how this was resolved",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dead Letter Queue Entry",
                "verbose_name_plural": "Dead Letter Queue Entries",
                "db_table": "core_dead_letter_queue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "-created_at"],
                        name="core_dead_l_is_reso_90631b_idx",
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="core_dead_l_priorit_2724f5_idx",
                    ),
                    models.Index(
                        fields=["task_name", "-created_at"],
                        name="core_dead_l_task_na_9a48fc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Celery task ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Task name (e.g., 'core.tasks.send_email')",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("started", "Started"),
                            ("progress", "In Progress"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("retry", "Retrying"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Task progress percentage (0-100)"
                    ),
                ),
                (
                    "progress_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Current progress message",
                        max_length=500,
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Task positional arguments",
                    ),
                ),
                (
                    "kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Task keyword arguments",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Task result data",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, default="", help_text="Error message if task failed"
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full traceback if task failed",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the task was created",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task started execution",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task completed (success or failure)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Result",
                "verbose_name_plural": "Task Results",
                "db_table": "core_task_result",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_task_r_created_0e2b4a_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_task_r_status_623124_idx",
                    ),
                    models.Index(
                        fields=["name", "-created_at"],
                        name="core_task_r_name_e55996_idx",
                    ),
                ],
            },
        ),
    ]
