# Generated by Django 5.2.6 on 2026-09-24 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todo_deleted_at_todo_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
            },
        ),
    ]
