#!/usr/bin/env python3
"""Fail when a guarded secret is missing from scripts/env_secrets.py.

The guards are the source of truth: every secret that docker-compose.yml or
deploy/ requires with ``${VAR:?...}``, that api/settings/prod.py refuses to
start without, or that docker-entrypoint.sh checks must be generated by
scripts/env_secrets.py, with a long enough value, and every value those
guards reject must count as unset there (so ``fill`` replaces it). Compose
must not fall back to a published value for a secret (``${VAR:-value}``).

Usage: python3 scripts/check_env_secrets.py [--root DIR]
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path
from types import ModuleType

SECRET_NAME = re.compile(r"SECRET|PASSWORD|_KEY$|TOKEN|BASIC_AUTH")
REQUIRED = re.compile(r"\$\{([A-Z][A-Z0-9_]*):?\?")
WEAK_DEFAULT = re.compile(r"\$\{([A-Z][A-Z0-9_]*):?-([^}]+)\}")
SETTINGS_GUARD = re.compile(r"ImproperlyConfigured\(\s*\"Set ([A-Z][A-Z0-9_]*)")
REJECTED_SET = re.compile(r"(_INSECURE_[A-Z_]+) = \{([^}]*)\}")
REJECTED_USE = re.compile(r"if ([A-Z][A-Z0-9_]*) in (_INSECURE_[A-Z_]+):")
SHELL_LENGTH = re.compile(r"\$\{#([A-Z][A-Z0-9_]*)\}\"? -lt (\d+)")
SHELL_CASE = re.compile(r"case \"\$([A-Z][A-Z0-9_]*)\" in\s*\n\s*([^)\n]+)\)")
QUOTED = re.compile(r"[\"']([^\"']+)[\"']")
DEPLOY_SUFFIXES = {".yml", ".yaml", ".json", ".toml", ".env", ".example"}


def load_env_secrets(root: Path) -> ModuleType:
    """Import ``root/scripts/env_secrets.py``."""
    path = root / "scripts" / "env_secrets.py"
    spec = importlib.util.spec_from_file_location("checked_env_secrets", path)
    if spec is None or spec.loader is None:
        raise FileNotFoundError(path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _compose_files(root: Path) -> list[Path]:
    files = sorted(root.glob("docker-compose*.yml")) + sorted(root.glob("compose*.yml"))
    deploy = root / "deploy"
    if deploy.is_dir():
        files += sorted(
            p for p in deploy.rglob("*") if p.is_file() and p.suffix in DEPLOY_SUFFIXES
        )
    return files


def _read(path: Path) -> str:
    return path.read_text() if path.exists() else ""


def find_problems(root: Path) -> list[str]:
    """Return one message per guard that scripts/env_secrets.py does not meet."""
    module = load_env_secrets(root)
    by_name = {secret.name: secret for secret in module.SECRETS}
    problems: list[str] = []

    def require(name: str, source: str, min_length: int = 0) -> None:
        secret = by_name.get(name)
        if secret is None:
            problems.append(f"{source}: {name} is required but not generated")
        elif secret.min_length < min_length:
            problems.append(
                f"{source}: {name} needs {min_length}+ characters; "
                f"env_secrets.py allows {secret.min_length}"
            )

    def rejects(name: str, value: str, source: str) -> None:
        secret = by_name.get(name)
        if secret is not None and not module.is_unset(secret, value):
            problems.append(f"{source}: rejected {name} value is not a placeholder")

    for path in _compose_files(root):
        text, source = path.read_text(), str(path.relative_to(root))
        for name in sorted(set(REQUIRED.findall(text))):
            if SECRET_NAME.search(name):
                require(name, source)
        for name, _default in WEAK_DEFAULT.findall(text):
            if SECRET_NAME.search(name):
                problems.append(f"{source}: {name} falls back to a published value")

    prod = _read(root / "api" / "settings" / "prod.py")
    for name in SETTINGS_GUARD.findall(prod):
        require(name, "api/settings/prod.py")
    rejected_sets = dict(REJECTED_SET.findall(prod))
    for name, set_name in REJECTED_USE.findall(prod):
        require(name, "api/settings/prod.py")
        for value in QUOTED.findall(rejected_sets.get(set_name, "")):
            rejects(name, value, "api/settings/prod.py")

    entrypoint = _read(root / "docker-entrypoint.sh")
    for name, length in SHELL_LENGTH.findall(entrypoint):
        require(name, "docker-entrypoint.sh", int(length))
    for name, patterns in SHELL_CASE.findall(entrypoint):
        for value in patterns.split("|"):
            rejects(name, value.strip().strip("'\""), "docker-entrypoint.sh")
    return problems


def main(argv: list[str] | None = None) -> int:
    """Print every problem; exit 1 when there is one."""
    parser = argparse.ArgumentParser(description="Check guarded secrets.")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    root = parser.parse_args(argv).root
    problems = find_problems(root)
    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        return 1
    print("Every guarded secret is generated by scripts/env_secrets.py.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
