#!/usr/bin/env python3
"""Generate the secrets that a project ``.env`` needs.

This is the one list of generated secrets. ``dnm init``, ``dnm setup``,
``just setup-env``, ``just setup-services``, ``scripts/setup.sh``,
``scripts/quickstart.sh`` and mattstack all call this file, and
docs/ENV_SECRETS.md documents the same list and the command line interface.
It uses the standard library only, so it runs before any dependency is
installed. No command prints a secret value.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import secrets
import string
import sys
import tempfile
from collections.abc import Iterable
from pathlib import Path
from typing import NamedTuple

ENV_FILE = ".env"
TEMPLATE_FILE = ".env.example"
INTERFACE_VERSION = 1
KEY_LENGTH = 64
PASSWORD_LENGTH = 32
MIN_KEY_LENGTH = 50
MIN_PASSWORD_LENGTH = 12
# Letters and digits only: no character needs quoting in .env, in a URL
# (redis://:PASSWORD@host) or in a shell argument, and Compose never sees "$".
_ALPHABET = string.ascii_letters + string.digits
# Values that were ever published in this repository's templates or compose
# defaults. A secret with one of these values counts as unset.
_PLACEHOLDERS = {
    "admin",
    "admin123",
    "admin-secret",
    "centrifugo-api-key",
    "centrifugo-token-secret",
    "changeme",
    "change_me",
    "devpassword",
    "password",
    "password123!",
    "placeholder",
    "postgres",
}
HEADER = (
    "# Generated by scripts/env_secrets.py. Never commit this file.\n"
    "# The secrets below belong to this environment only. Generate a new set\n"
    "# for every other environment (staging, production) and never reuse them.\n"
)


class Secret(NamedTuple):
    """One generated variable."""

    name: str
    min_length: int
    # True when a data volume stores the value at first start (Postgres,
    # Neo4j). Changing it in .env afterwards locks the application out, so
    # `fill` never replaces a value that is already set.
    stored: bool = False
    # Prefix written before the random part, e.g. "admin:" for basic auth.
    prefix: str = ""

    @property
    def kind(self) -> str:
        """Return ``key``, ``password`` or ``basic_auth``."""
        if self.prefix:
            return "basic_auth"
        return "key" if self.min_length >= MIN_KEY_LENGTH else "password"

    @property
    def length(self) -> int:
        """Return the length of the random part of a generated value."""
        return KEY_LENGTH if self.kind == "key" else PASSWORD_LENGTH


SECRETS: tuple[Secret, ...] = (
    Secret("SECRET_KEY", MIN_KEY_LENGTH),
    Secret("NINJA_JWT_SIGNING_KEY", MIN_KEY_LENGTH),
    Secret("CENTRIFUGO_TOKEN_SECRET", MIN_KEY_LENGTH),
    Secret("CENTRIFUGO_API_KEY", MIN_KEY_LENGTH),
    Secret("CENTRIFUGO_ADMIN_SECRET", MIN_KEY_LENGTH),
    Secret("CENTRIFUGO_ADMIN_PASSWORD", MIN_PASSWORD_LENGTH),
    Secret("DJANGO_MCP_AUTH_TOKEN", MIN_KEY_LENGTH),
    Secret("DB_PASSWORD", MIN_PASSWORD_LENGTH, stored=True),
    Secret("REDIS_PASSWORD", MIN_PASSWORD_LENGTH),
    Secret("FLOWER_BASIC_AUTH", MIN_PASSWORD_LENGTH, prefix="admin:"),
    Secret("NEO4J_PASSWORD", MIN_PASSWORD_LENGTH, stored=True),
    Secret("SUPERUSER_PASSWORD", MIN_PASSWORD_LENGTH),
)
NAMES = tuple(secret.name for secret in SECRETS)


def generate(secret: Secret) -> str:
    """Return a new random value for ``secret``."""
    random_part = "".join(secrets.choice(_ALPHABET) for _ in range(secret.length))
    return secret.prefix + random_part


def describe() -> dict[str, object]:
    """Return the machine-readable list printed by ``list --json``."""
    fields = ("name", "kind", "length", "min_length", "stored", "prefix")
    return {
        "version": INTERFACE_VERSION,
        "secrets": [{f: getattr(s, f) for f in fields} for s in SECRETS],
    }


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def read_env(path: Path) -> dict[str, str]:
    """Parse the active ``KEY=VALUE`` lines of an env file."""
    values: dict[str, str] = {}
    for line in path.read_text().splitlines():
        key, separator, value = line.partition("=")
        key = key.strip()
        if separator and key and not key.startswith("#"):
            values[key] = _unquote(value)
    return values


def _secret_part(secret: Secret, value: str) -> str:
    """Strip the non-secret prefix, e.g. the user in ``user:password``."""
    return value.partition(":")[2] if secret.prefix else value


def is_unset(secret: Secret, value: str | None) -> bool:
    """Return True when ``value`` is empty or a published placeholder."""
    lowered = _secret_part(secret, value or "").lower()
    return (
        not lowered
        or lowered in _PLACEHOLDERS
        or "change-in-production" in lowered
        or lowered.startswith(("your-", "dev-", "development-"))
    )


def is_weak(secret: Secret, value: str | None) -> bool:
    """Return True when ``value`` is unset, a placeholder, or too short."""
    return (
        is_unset(secret, value)
        or len(_secret_part(secret, value or "")) < secret.min_length
    )


def _apply(lines: list[str], values: dict[str, str]) -> list[str]:
    """Set each key in ``values``: replace, uncomment, or append."""
    pending = dict(values)
    active = {line.partition("=")[0].strip() for line in lines if "=" in line}
    result: list[str] = []
    for line in lines:
        key = line.partition("=")[0].strip()
        commented = key.lstrip("#").strip()
        if "=" in line and key in values:
            result.append(f"{key}={values[key]}")
            pending.pop(key, None)
        elif (
            "=" in line
            and key.startswith("#")
            and commented in pending
            and commented not in active
        ):
            result.append(f"{commented}={pending.pop(commented)}")
        else:
            result.append(line)
    if pending:
        result += ["", "# Generated secrets"]
        result += [f"{key}={value}" for key, value in pending.items()]
    return result


def write_private(path: Path, text: str, *, replace: bool = False) -> None:
    """Write ``text`` with mode 0600. Without ``replace``, refuse an existing file."""
    if not replace:
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(descriptor, "w") as handle:
            handle.write(text)
        path.chmod(0o600)
        return
    # mkstemp creates the file with mode 0600.
    descriptor, name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    temporary = Path(name)
    try:
        with os.fdopen(descriptor, "w") as handle:
            handle.write(text)
        temporary.replace(path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def ensure_gitignored(env_file: Path) -> bool:
    """Make the .gitignore next to ``env_file`` ignore it; True when changed.

    Patterns are matched like git does: the last matching line wins, so a
    ``!.env.example`` exception does not hide an ignored ``.env``.
    """
    gitignore = env_file.parent / ".gitignore"
    lines = gitignore.read_text().splitlines() if gitignore.exists() else []
    ignored = False
    for raw in lines:
        pattern = raw.strip()
        if not pattern or pattern.startswith("#"):
            continue
        negated = pattern.startswith("!")
        if fnmatch.fnmatchcase(env_file.name, pattern.lstrip("!").lstrip("/")):
            ignored = not negated
    if ignored:
        return False
    prefix = "\n" if lines and lines[-1].strip() else ""
    with gitignore.open("a") as handle:
        handle.write(f"{prefix}# Local environment and secrets\n{env_file.name}\n")
    return True


def create_env(
    env_file: Path,
    template: Path | None = None,
    overrides: dict[str, str] | None = None,
    names: Iterable[str] = NAMES,
) -> list[str]:
    """Write ``env_file`` from ``template`` with fresh secrets.

    ``template=None`` writes the header and the secrets only. ``names``
    limits which secrets are generated. ``overrides`` sets other values.
    Returns the names of the generated secrets. Raises FileExistsError when
    ``env_file`` exists.
    """
    wanted = set(names)
    lines = template.read_text().splitlines() if template else []
    values = {s.name: generate(s) for s in SECRETS if s.name in wanted}
    values.update(overrides or {})
    write_private(env_file, HEADER + "\n".join(_apply(lines, values)) + "\n")
    ensure_gitignored(env_file)
    return [s.name for s in SECRETS if s.name in wanted - set(overrides or {})]


def fill_env(env_file: Path) -> tuple[list[str], list[str]]:
    """Generate the unset secrets in an existing ``env_file``.

    Only empty, missing or published placeholder values change; a value you
    chose is kept even when it is short. A stored secret (database password)
    with a placeholder value is left alone, because the data volume already
    uses it. Returns ``(filled, skipped)`` names.
    """
    current = read_env(env_file)
    unset = [s for s in SECRETS if is_unset(s, current.get(s.name))]
    skipped = [s.name for s in unset if s.stored and current.get(s.name)]
    values = {s.name: generate(s) for s in unset if s.name not in skipped}
    jwt_key = current.get("NINJA_JWT_SIGNING_KEY")
    if jwt_key and jwt_key == current.get("SECRET_KEY"):
        values["NINJA_JWT_SIGNING_KEY"] = generate(SECRETS[1])
    if values:
        lines = _apply(env_file.read_text().splitlines(), values)
        write_private(env_file, "\n".join(lines) + "\n", replace=True)
    ensure_gitignored(env_file)
    return list(values), skipped


def weak_secrets(env_file: Path) -> list[str]:
    """Return the names of weak secrets in ``env_file``."""
    current = read_env(env_file)
    names = [s.name for s in SECRETS if is_weak(s, current.get(s.name))]
    secret_key = current.get("SECRET_KEY")
    if secret_key and secret_key == current.get("NINJA_JWT_SIGNING_KEY"):
        names.append("NINJA_JWT_SIGNING_KEY (equals SECRET_KEY)")
    return names


def _name_list(value: str) -> list[str]:
    names = [name.strip() for name in value.split(",") if name.strip()]
    unknown = sorted(set(names) - set(NAMES))
    if unknown:
        raise argparse.ArgumentTypeError(f"unknown secrets: {', '.join(unknown)}")
    return names


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate the secrets in .env.")
    parser.add_argument("command", choices=["create", "fill", "check", "list"])
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="project root")
    parser.add_argument("--env-file", type=Path, help="default: ROOT/.env")
    parser.add_argument("--json", action="store_true", help="list: print JSON")
    templates = parser.add_mutually_exclusive_group()
    templates.add_argument("--template", type=Path, help="default: ROOT/.env.example")
    templates.add_argument(
        "--no-template", action="store_true", help="create: write the secrets only"
    )
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--only", type=_name_list, help="create: A,B")
    selection.add_argument("--exclude", type=_name_list, help="create: A,B")
    parser.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="create: non-secret value, e.g. TASK_BACKEND=huey",
    )
    return parser


def _create(args: argparse.Namespace, env_file: Path) -> int:
    template = None
    if not args.no_template:
        template = args.template or args.root / TEMPLATE_FILE
        if args.template is None and not template.exists():
            template = None
    names = args.only or [n for n in NAMES if n not in (args.exclude or [])]
    overrides = dict(item.partition("=")[::2] for item in args.set)
    try:
        created = create_env(env_file, template, overrides, names)
    except FileExistsError:
        print(f"{env_file} exists; leaving it unchanged.", file=sys.stderr)
        return 1
    count = len(created)
    print(f"Created {env_file} (mode 600) with {count} generated secrets: ", end="")
    print(", ".join(created))
    return 0


def _fill(env_file: Path) -> int:
    filled, skipped = fill_env(env_file)
    print(f"Generated {len(filled)} secrets in {env_file}: {', '.join(filled)}")
    stored = [s.name for s in SECRETS if s.stored and s.name in filled]
    if stored:
        print(
            f"New {', '.join(stored)}: if that data volume already exists, set "
            "the password it was created with instead.",
            file=sys.stderr,
        )
    if skipped:
        print(
            "Placeholder values left unchanged, because a data volume stores "
            f"them; set real ones and recreate the volume: {', '.join(skipped)}",
            file=sys.stderr,
        )
    return 0


def _check(env_file: Path) -> int:
    weak = weak_secrets(env_file)
    if weak:
        print(
            f"Weak or unset secrets in {env_file}: {', '.join(weak)}", file=sys.stderr
        )
        return 1
    print(f"All {len(SECRETS)} generated secrets in {env_file} are set.")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the command line interface."""
    args = _parser().parse_args(argv)
    env_file: Path = args.env_file or args.root / ENV_FILE
    if args.command == "list":
        print(json.dumps(describe(), indent=2) if args.json else "\n".join(NAMES))
        return 0
    if args.command == "create":
        return _create(args, env_file)
    if not env_file.exists():
        print(
            f"{env_file} does not exist. Run: python3 scripts/env_secrets.py create",
            file=sys.stderr,
        )
        return 1
    return _fill(env_file) if args.command == "fill" else _check(env_file)


if __name__ == "__main__":
    sys.exit(main())
